### PR TITLE
fix: improve tag list

### LINKED ISSUE #53: config bug
"configPath" gets saved to the filesystem. This information is not useful in the file.

### LINKED ISSUE #59: git bug
UnhandledPromiseRejectionWarning: Error: Command failed: git config --get remote.origin.url

Executed in main branch

### PR DESCRIPTION
**Pull request by BioPhoton**
This should be read: https://github.com/timdeschryver/deprecation-manager/pull/61/files#r473468436

Things implemented:
- Tries to unify all our methods to take config and crawledRelease (this caused so many file changes)
- separates dynamic vs static data. (move all changing parts out of config and into crawled release)
- Added more information to a tag ({semver: string, tagName: string, date: string})
- created tag filtering by tagFormat
- added yargs param ensurance
- closes #59 closes #53

### CODE REVIEW

File: packages/deprecation-crawler/src/lib/config.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@ import {
   CRAWLER_CONFIG_PATH,
   TSCONFIG_PATH,
   DEPRECATIONS_OUTPUT_DIRECTORY,
+  TAG_FORMAT_TEMPLATE,
```
Comment (BioPhoton) [inline packages/deprecation-crawler/src/lib/config.ts:9]: user to find git tags

File: packages/deprecation-crawler/src/lib/config.ts [hunk 2]
```diff
@@ -32,21 +33,6 @@ export async function getConfig(): Promise<CrawlConfig> {
...
-    : ''
-  )
-    .toString()
-    .trim();
-
-  // if no param is given it is '' if param with no value is given it is true
-  const argTagGiven = argTag !== 'true' && argTag !== '';
-  // select the string value if passed, otherwise select the first item in the list
-  const gitTag = argTagGiven ? argTag : undefined;
-
```
Comment (BioPhoton) [inline packages/deprecation-crawler/src/lib/config.ts:49]: moved into crawl task

File: packages/deprecation-crawler/src/lib/config.ts [hunk 3]
```diff
@@ -88,11 +74,11 @@ export async function getConfig(): Promise<CrawlConfig> {
 
   const config = {
     outputFormatters: ['tagBasedMarkdown', 'groupBasedMarkdown'],
+    tagFormat: TAG_FORMAT_TEMPLATE,
     groups: [],
     configPath: crawlerConfigPath,
     ...repoConfig,
     ...userConfig,
-    gitTag,
```
Comment (BioPhoton) [inline packages/deprecation-crawler/src/lib/config.ts:95]: removed from config and added to release

**Comment by BioPhoton** [comment]
Hi @timdeschryver, the PR works now but is breaking the tests because the comments changed.

Could you help me to understand how the tests work?

**Comment by timdeschryver** [comment]
@BioPhoton I've added a commit to this PR that logs the error if one occurs while running the crawler.
That was the reason these tests are failing, I'm getting:

```
  Failed: "(node:1896) UnhandledPromiseRejectionWarning: Error: Tag name master passed over cli is not in the list of releases.
```

File: .github/workflows/ci.yml [hunk 4]
```diff
@@ -21,6 +21,6 @@ jobs:
       - name: install
         run: yarn
       - name: build
-        run: yarn build
+        run: npm run build
```
Comment (BioPhoton) [inline .github/workflows/ci.yml:24]: I had to change this because of following error:

 `$ npm run build && nx run-many --target=test --all
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1597882447464-0.20033904016625392/node but npm is using /opt/hostedtoolcache/node/12.18.3/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.`

Unfortunately, I have no clear answer of what caused this issue. I can imagine one of the added packages ` semver`  or `lodash-es`.

Comment (timdeschryver) [reply .github/workflows/ci.yml:24]: That's super weird 🤷‍♂️

File: packages/deprecation-crawler/src/lib/models.ts [hunk 5]
```diff
@@ -73,7 +83,7 @@ export interface RawDeprecation {
 }
 
 export interface CrawledRelease {
-  gitTag: string;
+  tag: string;
```
Comment (timdeschryver) [inline packages/deprecation-crawler/src/lib/models.ts:86]: @BioPhoton I removed the `branch` property here as it wasn't used.
I was confused by it 😅

**Review by timdeschryver — APPROVED** [review]
